# Generated by Django 5.2 on 2025-04-17 03:28

from django.db import migrations
def create_permissions(apps, schema_editor):
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    CustomUser = apps.get_model('accounts', 'CustomUser')

    # Create a new permission for the User model
    content_type = ContentType.objects.get_for_model(CustomUser)
    Permission.objects.get_or_create(
        codename='add_post',
        name='Can add post',
        content_type=content_type,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_permissions),
    ]
